### ISSUE TITLE
Tracking for issues still at old GitLab repository

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/rust-riot-wrappers#26]
Issues open when this repository moved over from https://gitlab.com/etonomy/riot-wrappers/ were not migrated for GitHub's lack of workflow for that, and are tracked there still:

* [ ] [1: Unrelated components should not interdepend](https://gitlab.com/etonomy/riot-wrappers/-/issues/1)
* [ ] [2: I2C: Add acquired type](https://gitlab.com/etonomy/riot-wrappers/-/issues/2)
* [ ] [5: LEDs: Switch to switch-hal](https://gitlab.com/etonomy/riot-wrappers/-/issues/5)
* [ ] [6: ZTimer: consider using fugit types for durations and points in time](https://gitlab.com/etonomy/riot-wrappers/-/issues/6)
* [ ] [8: vfs abstraction violates file system requirements](https://gitlab.com/etonomy/riot-wrappers/-/issues/8)
* [ ] [9: Termination: Use stabilized trait](https://gitlab.com/etonomy/riot-wrappers/-/issues/9)
* [ ] [10: cstr: Use from core](https://gitlab.com/etonomy/riot-wrappers/-/issues/10)

**Comment by chrysn** [comment]
The fugit issue is now superseded by the more general issue https://github.com/RIOT-OS/rust-riot-wrappers/issues/112.
